"use client";

import React from "react";
import Navbar from "../components/UI/Navbar";
import BottomMenu from "../components/UI/BottomMenu";
import MobileNavbar from "../components/UI/MobileNavbar";
import Footer from "../components/UI/Footer";
import { Toaster } from "react-hot-toast";
import "../app/globals.css";

const Terms = () => {
  return (
    <>
      <Toaster />

      {/* Navbar for larger screens */}
      <div className="hidden md:block">
        <Navbar />
      </div>

      {/* Navbar for mobile */}
      <div className="block md:hidden">
        <MobileNavbar />
      </div>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-14 md:py-12 mt-16 md:mt-24 space-y-10">
        <h1 className="text-3xl md:text-4xl font-bold text-center text-red-600">
          Terms & Conditions
        </h1>
        <div className="bg-white shadow-lg p-6 md:p-8 rounded-xl border-t-4 border-red-500">
          <div className="text-sm md:text-base leading-relaxed space-y-6 text-gray-700">
            <p>
              1. This document is an electronic record in terms of the
              Information Technology Act, 2000, and rules thereunder, as
              applicable. This electronic record is generated by a computer
              system and does not require any physical or digital signatures.
            </p>
            <p>
              2. This document is published in accordance with the provisions of
              Rule 3 (1) of the Information Technology (Intermediaries
              Guidelines) Rules, 2011, requiring publishing the rules and
              regulations, privacy policy, and Terms of Use for access or usage
              of the domain name https://9bets.pages.dev/ (Website), including
              the related mobile site and mobile application (hereinafter
              referred to as &quot;Platform&quot;).
            </p>
            <p>
              3. The Platform is owned by General Store, a company incorporated
              under the Companies Act, 1956, with its registered office at
              Marketing Yard Shop No. 90 Amreli Road Babra (hereinafter referred
              to as &quot;Platform Owner,&quot; &quot;we,&quot; &quot;us,&quot;
              &quot;our&quot;).
            </p>
            <p>
              4. Your use of the Platform and services and tools are governed by
              the following terms and conditions (&quot;Terms of Use&quot;) as
              applicable to the Platform, including the applicable policies
              which are incorporated herein by reference. By using the Platform,
              you shall be contracting with the Platform Owner, and these terms
              and conditions constitute your binding obligations.
            </p>
            <p>
              5. For the purpose of these Terms of Use, wherever the context so
              requires, &quot;you,&quot; &quot;your,&quot; or &quot;user&quot;
              shall mean any natural or legal person who has agreed to become a
              user/buyer on the Platform.
            </p>
            <p>
              6. ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES
              YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS
              OF USE. PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.
            </p>
            <p>
              7. The use of the Platform and/or availing of our Services is
              subject to the following Terms of Use:
            </p>
            <ol className="list-decimal ml-6 space-y-3 text-gray-700">
              <li>
                You agree to provide true, accurate, and complete information
                during and after registration, and you are responsible for all
                actions done through the use of your registered account on the
                Platform.
              </li>
              <li>
                Neither we nor any third parties provide any warranty or
                guarantee regarding the accuracy, timeliness, performance,
                completeness, or suitability of the information and materials
                offered on this website or through the Services.
              </li>
              <li>
                Your use of our Services and the Platform is at your own risk.
                We shall not be liable to you in any manner for such use.
              </li>
              <li>
                The contents of the Platform and Services are proprietary to us,
                and you will not claim any intellectual property rights, title,
                or interest in its contents, including design, layout, and
                graphics.
              </li>
              <li>
                Unauthorized use of the Platform and/or Services may lead to
                actions against you as per these Terms of Use and applicable
                laws.
              </li>
              <li>
                You agree to pay us for the charges associated with availing the
                Services.
              </li>
              <li>
                You agree not to use the Platform and/or Services for unlawful
                or forbidden purposes as defined by these Terms or applicable
                laws.
              </li>
              <li>
                You acknowledge that the Platform and Services may contain links
                to third-party websites, governed by their own terms of use and
                privacy policies.
              </li>
              <li>
                Upon initiating a transaction, you enter into a legally binding
                contract with the Platform Owner for the Services.
              </li>
              <li>
                You shall indemnify and hold harmless the Platform Owner and its
                affiliates from any claims or actions arising out of your breach
                of these Terms.
              </li>
              <li>
                These Terms and any dispute relating to them shall be governed
                by and construed in accordance with the laws of India.
              </li>
              <li>
                Disputes arising from these Terms shall be subject to the
                exclusive jurisdiction of the courts in Amreli and Gujarat.
              </li>
            </ol>
          </div>
        </div>
      </div>

      {/* Footer for larger screens */}
      <div className="hidden md:block">
        <Footer />
      </div>
      <div className="block md:hidden fixed bottom-0 w-full z-20">
        <BottomMenu />
      </div>
    </>
  );
};

export default Terms;
